# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URVERSION = $(shell urweb -version)
UR_CPP = $(shell $(shell urweb -print-ccompiler) -print-prog-name=g++)
UR_INCL = -I$(shell urweb -print-cinclude)
.PHONY: ./all
./all: ./Makefile ./demo/Demo2.db ./demo/Demo2.exe ./demo/Demo2.sql ./test/Stress1.db ./test/Stress1.exe ./test/Stress1.sql ./test2/Notify.db ./test2/Notify.exe ./test2/Notify.sql ./test2/Simple1.db ./test2/Simple1.exe ./test2/Simple1.sql ./test2/Stdout.db ./test2/Stdout.exe ./test2/Stdout.sql ./test2/Stress.db ./test2/Stress.exe ./test2/Stress.sql
./demo/Demo2.db: ./Makefile ./demo/Demo2.exe ./demo/Demo2.sql
	dropdb --if-exists Demo2
	createdb Demo2
	psql -f ./demo/Demo2.sql Demo2
	touch ./demo/Demo2.db
./test2/Notify.db: ./Makefile ./test2/Notify.exe ./test2/Notify.sql
	dropdb --if-exists Notify
	createdb Notify
	psql -f ./test2/Notify.sql Notify
	touch ./test2/Notify.db
./test2/Stress.db: ./Makefile ./test2/Stress.exe ./test2/Stress.sql
	dropdb --if-exists Stress
	createdb Stress
	psql -f ./test2/Stress.sql Stress
	touch ./test2/Stress.db
./test2/Stdout.db: ./Makefile ./test2/Stdout.exe ./test2/Stdout.sql
	dropdb --if-exists Stdout
	createdb Stdout
	psql -f ./test2/Stdout.sql Stdout
	touch ./test2/Stdout.db
./test2/Simple1.db: ./Makefile ./test2/Simple1.exe ./test2/Simple1.sql
	dropdb --if-exists Simple1
	createdb Simple1
	psql -f ./test2/Simple1.sql Simple1
	touch ./test2/Simple1.db
./test/Stress1.db: ./Makefile ./test/Stress1.exe ./test/Stress1.sql
	dropdb --if-exists Stress1
	createdb Stress1
	psql -f ./test/Stress1.sql Stress1
	touch ./test/Stress1.db
./.cake3/tmp___test2_Notify_in_2: ./Makefile ./lib.urp ./test2/Notify.ur ./test2/Templ.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/string  ;\
	echo \.\.\/test2\/Templ  ;\
	echo \.\.\/test2\/Notify  ;\
	) > ./.cake3/tmp___test2_Notify_in_2
./.cake3/tmp___test2_Notify_in_1: ./Makefile ./lib.urp ./test2/Notify.ur ./test2/Templ.ur
	( \
	echo debug  ;\
	echo allow\ url\ http\:\/\/code\.jquery\.com\/ui\/1\.10\.3\/jquery\-ui\.js  ;\
	echo allow\ mime\ text\/javascript  ;\
	echo allow\ mime\ text\/css  ;\
	echo allow\ mime\ image\/jpeg  ;\
	echo allow\ mime\ image\/png  ;\
	echo allow\ mime\ image\/gif  ;\
	echo database\ dbname\=Notify  ;\
	echo safeGet\ Notify\/main  ;\
	echo safeGet\ Notify\/job\_monitor  ;\
	echo safeGet\ Notify\/src\_monitor  ;\
	echo safeGet\ Notify\/job\_start  ;\
	echo safeGet\ Notify\/finished  ;\
	echo safeGet\ Notify\/cleanup  ;\
	echo safeGet\ Notify\/monitor  ;\
	echo safeGet\ Notify\/run  ;\
	echo safeGet\ Notify\/C\/callback  ;\
	echo safeGet\ Notify\/C\/C\/callback  ;\
	echo safeGet\ Notify\/cnt  ;\
	echo safeGet\ Notify\/Find\/C\/callback  ;\
	echo safeGet\ Notify\/Cat\/C\/callback  ;\
	echo safeGet\ Notify\/viewsrc  ;\
	echo safeGet\ Notify\/status  ;\
	echo safeGet\ Notify\/lastline  ;\
	echo safeGet\ Notify\/longrunning  ;\
	echo sql\ \.\.\/test2\/Notify\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___test2_Notify_in_1
./.cake3/tmp___lib_in_2: ./Makefile ./Callback.ur ./Callback.urs ./CallbackFFI.h ./CallbackFFI.o ./CallbackNotify.ur ./CallbackNotify.urs ./CallbackNotify2.ur ./CallbackNotify2.urs
	( \
	echo   ;\
	echo $$\/list  ;\
	echo \.\/Callback  ;\
	echo \.\/CallbackNotify  ;\
	echo \.\/CallbackNotify2  ;\
	) > ./.cake3/tmp___lib_in_2
./.cake3/tmp___lib_in_1: ./Makefile ./Callback.ur ./Callback.urs ./CallbackFFI.h ./CallbackFFI.o ./CallbackNotify.ur ./CallbackNotify.urs ./CallbackNotify2.ur ./CallbackNotify2.urs
	( \
	echo ffi\ \.\/CallbackFFI  ;\
	echo include\ \.\/CallbackFFI\.h  ;\
	echo safeGet\ Callback\/Default\/callback  ;\
	echo safeGet\ CallbackNotify\/Default\/C\/callback  ;\
	echo link\ \.\/CallbackFFI\.o  ;\
	echo link\ \-lstdc\+\+  ;\
	) > ./.cake3/tmp___lib_in_1
./.cake3/tmp___test2_Stress_in_2: ./Makefile ./lib.urp ./test2/Stress.ur ./test2/Templ.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/string  ;\
	echo \.\.\/test2\/Templ  ;\
	echo \.\.\/test2\/Stress  ;\
	) > ./.cake3/tmp___test2_Stress_in_2
./.cake3/tmp___test2_Stress_in_1: ./Makefile ./lib.urp ./test2/Stress.ur ./test2/Templ.ur
	( \
	echo debug  ;\
	echo allow\ url\ http\:\/\/code\.jquery\.com\/ui\/1\.10\.3\/jquery\-ui\.js  ;\
	echo allow\ mime\ text\/javascript  ;\
	echo allow\ mime\ text\/css  ;\
	echo allow\ mime\ image\/jpeg  ;\
	echo allow\ mime\ image\/png  ;\
	echo allow\ mime\ image\/gif  ;\
	echo database\ dbname\=Stress  ;\
	echo safeGet\ Stress\/main  ;\
	echo safeGet\ Stress\/job\_monitor  ;\
	echo safeGet\ Stress\/src\_monitor  ;\
	echo safeGet\ Stress\/job\_start  ;\
	echo safeGet\ Stress\/finished  ;\
	echo safeGet\ Stress\/cleanup  ;\
	echo safeGet\ Stress\/monitor  ;\
	echo safeGet\ Stress\/run  ;\
	echo safeGet\ Stress\/C\/callback  ;\
	echo safeGet\ Stress\/C\/C\/callback  ;\
	echo safeGet\ Stress\/cnt  ;\
	echo safeGet\ Stress\/Find\/C\/callback  ;\
	echo safeGet\ Stress\/Cat\/C\/callback  ;\
	echo safeGet\ Stress\/viewsrc  ;\
	echo safeGet\ Stress\/status  ;\
	echo safeGet\ Stress\/lastline  ;\
	echo safeGet\ Stress\/longrunning  ;\
	echo sql\ \.\.\/test2\/Stress\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___test2_Stress_in_1
./.cake3/tmp___test2_Stdout_in_2: ./Makefile ./lib.urp ./test2/Stdout.ur ./test2/Templ.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/string  ;\
	echo \.\.\/test2\/Templ  ;\
	echo \.\.\/test2\/Stdout  ;\
	) > ./.cake3/tmp___test2_Stdout_in_2
./.cake3/tmp___test2_Stdout_in_1: ./Makefile ./lib.urp ./test2/Stdout.ur ./test2/Templ.ur
	( \
	echo debug  ;\
	echo allow\ url\ http\:\/\/code\.jquery\.com\/ui\/1\.10\.3\/jquery\-ui\.js  ;\
	echo allow\ mime\ text\/javascript  ;\
	echo allow\ mime\ text\/css  ;\
	echo allow\ mime\ image\/jpeg  ;\
	echo allow\ mime\ image\/png  ;\
	echo allow\ mime\ image\/gif  ;\
	echo database\ dbname\=Stdout  ;\
	echo safeGet\ Stdout\/main  ;\
	echo safeGet\ Stdout\/job\_monitor  ;\
	echo safeGet\ Stdout\/src\_monitor  ;\
	echo safeGet\ Stdout\/job\_start  ;\
	echo safeGet\ Stdout\/finished  ;\
	echo safeGet\ Stdout\/cleanup  ;\
	echo safeGet\ Stdout\/monitor  ;\
	echo safeGet\ Stdout\/run  ;\
	echo safeGet\ Stdout\/C\/callback  ;\
	echo safeGet\ Stdout\/C\/C\/callback  ;\
	echo safeGet\ Stdout\/cnt  ;\
	echo safeGet\ Stdout\/Find\/C\/callback  ;\
	echo safeGet\ Stdout\/Cat\/C\/callback  ;\
	echo safeGet\ Stdout\/viewsrc  ;\
	echo safeGet\ Stdout\/status  ;\
	echo safeGet\ Stdout\/lastline  ;\
	echo safeGet\ Stdout\/longrunning  ;\
	echo sql\ \.\.\/test2\/Stdout\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___test2_Stdout_in_1
./.cake3/tmp___test2_Simple1_in_2: ./Makefile ./lib.urp ./test2/Simple1.ur ./test2/Templ.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/string  ;\
	echo \.\.\/test2\/Templ  ;\
	echo \.\.\/test2\/Simple1  ;\
	) > ./.cake3/tmp___test2_Simple1_in_2
./.cake3/tmp___test2_Simple1_in_1: ./Makefile ./lib.urp ./test2/Simple1.ur ./test2/Templ.ur
	( \
	echo debug  ;\
	echo allow\ url\ http\:\/\/code\.jquery\.com\/ui\/1\.10\.3\/jquery\-ui\.js  ;\
	echo allow\ mime\ text\/javascript  ;\
	echo allow\ mime\ text\/css  ;\
	echo allow\ mime\ image\/jpeg  ;\
	echo allow\ mime\ image\/png  ;\
	echo allow\ mime\ image\/gif  ;\
	echo database\ dbname\=Simple1  ;\
	echo safeGet\ Simple1\/main  ;\
	echo safeGet\ Simple1\/job\_monitor  ;\
	echo safeGet\ Simple1\/src\_monitor  ;\
	echo safeGet\ Simple1\/job\_start  ;\
	echo safeGet\ Simple1\/finished  ;\
	echo safeGet\ Simple1\/cleanup  ;\
	echo safeGet\ Simple1\/monitor  ;\
	echo safeGet\ Simple1\/run  ;\
	echo safeGet\ Simple1\/C\/callback  ;\
	echo safeGet\ Simple1\/C\/C\/callback  ;\
	echo safeGet\ Simple1\/cnt  ;\
	echo safeGet\ Simple1\/Find\/C\/callback  ;\
	echo safeGet\ Simple1\/Cat\/C\/callback  ;\
	echo safeGet\ Simple1\/viewsrc  ;\
	echo safeGet\ Simple1\/status  ;\
	echo safeGet\ Simple1\/lastline  ;\
	echo safeGet\ Simple1\/longrunning  ;\
	echo sql\ \.\.\/test2\/Simple1\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___test2_Simple1_in_1
./.cake3/tmp___test_Stress1_in_2: ./Makefile ./lib.urp ./test/Stress1.ur ./test2/Templ.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/string  ;\
	echo \.\.\/test2\/Templ  ;\
	echo \.\.\/test\/Stress1  ;\
	) > ./.cake3/tmp___test_Stress1_in_2
./.cake3/tmp___test_Stress1_in_1: ./Makefile ./lib.urp ./test/Stress1.ur ./test2/Templ.ur
	( \
	echo debug  ;\
	echo allow\ url\ http\:\/\/code\.jquery\.com\/ui\/1\.10\.3\/jquery\-ui\.js  ;\
	echo allow\ mime\ text\/javascript  ;\
	echo allow\ mime\ text\/css  ;\
	echo allow\ mime\ image\/jpeg  ;\
	echo allow\ mime\ image\/png  ;\
	echo allow\ mime\ image\/gif  ;\
	echo database\ dbname\=Stress1  ;\
	echo safeGet\ Stress1\/main  ;\
	echo safeGet\ Stress1\/job\_monitor  ;\
	echo safeGet\ Stress1\/src\_monitor  ;\
	echo safeGet\ Stress1\/job\_start  ;\
	echo safeGet\ Stress1\/finished  ;\
	echo safeGet\ Stress1\/cleanup  ;\
	echo safeGet\ Stress1\/monitor  ;\
	echo safeGet\ Stress1\/run  ;\
	echo safeGet\ Stress1\/C\/callback  ;\
	echo safeGet\ Stress1\/C\/C\/callback  ;\
	echo safeGet\ Stress1\/cnt  ;\
	echo safeGet\ Stress1\/Find\/C\/callback  ;\
	echo safeGet\ Stress1\/Cat\/C\/callback  ;\
	echo safeGet\ Stress1\/viewsrc  ;\
	echo safeGet\ Stress1\/status  ;\
	echo safeGet\ Stress1\/lastline  ;\
	echo safeGet\ Stress1\/longrunning  ;\
	echo sql\ \.\.\/test\/Stress1\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___test_Stress1_in_1
.PHONY: ./demo
./demo: ./Makefile ./demo/Demo2.db
./.cake3/tmp___demo_Demo2_in_2: ./Makefile ./demo/Demo2.ur ./demo/Demo2.urs ./lib.urp
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/char  ;\
	echo $$\/string  ;\
	echo \.\.\/demo\/Demo2  ;\
	) > ./.cake3/tmp___demo_Demo2_in_2
./.cake3/tmp___demo_Demo2_in_1: ./Makefile ./demo/Demo2.ur ./demo/Demo2.urs ./lib.urp
	( \
	echo database\ dbname\=Demo2  ;\
	echo safeGet\ Demo2\/main  ;\
	echo safeGet\ Demo2\/monitor  ;\
	echo allow\ env\ PING  ;\
	echo sql\ \.\.\/demo\/Demo2\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___demo_Demo2_in_1
.PHONY: ./lib
./lib: ./Makefile ./lib.urp
.INTERMEDIATE: ./.fix-multy1
./.fix-multy1: ./Makefile ./demo/Demo2.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./demo/Demo2
.INTERMEDIATE: ./.fix-multy2
./.fix-multy2: ./Makefile ./test/Stress1.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test/Stress1
.INTERMEDIATE: ./.fix-multy3
./.fix-multy3: ./Makefile ./test2/Notify.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test2/Notify
.INTERMEDIATE: ./.fix-multy4
./.fix-multy4: ./Makefile ./test2/Simple1.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test2/Simple1
.INTERMEDIATE: ./.fix-multy5
./.fix-multy5: ./Makefile ./test2/Stdout.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test2/Stdout
.INTERMEDIATE: ./.fix-multy6
./.fix-multy6: ./Makefile ./test2/Stress.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test2/Stress
./CallbackFFI.o: ./Makefile ./CallbackFFI.cpp $(call GUARD,UR_CFLAGS) $(call GUARD,UR_CPP) $(call GUARD,UR_INCL)
	$(UR_CPP) -c $(UR_CFLAGS) $(UR_INCL) -std=c++11 -o ./CallbackFFI.o ./CallbackFFI.cpp
./demo/Demo2.exe: ./.fix-multy1
./demo/Demo2.sql: ./.fix-multy1
./demo/Demo2.urp: ./Makefile ./.cake3/tmp___demo_Demo2_in_1 ./.cake3/tmp___demo_Demo2_in_2
	cat ./.cake3/tmp___demo_Demo2_in_1 > ./demo/Demo2.urp
	cat ./.cake3/tmp___demo_Demo2_in_2 >> ./demo/Demo2.urp
./lib.urp: ./Makefile ./.cake3/tmp___lib_in_1 ./.cake3/tmp___lib_in_2
	cat ./.cake3/tmp___lib_in_1 > ./lib.urp
	cat ./.cake3/tmp___lib_in_2 >> ./lib.urp
./test/Stress1.exe: ./.fix-multy2
./test/Stress1.sql: ./.fix-multy2
./test/Stress1.urp: ./Makefile ./.cake3/tmp___test_Stress1_in_1 ./.cake3/tmp___test_Stress1_in_2
	cat ./.cake3/tmp___test_Stress1_in_1 > ./test/Stress1.urp
	cat ./.cake3/tmp___test_Stress1_in_2 >> ./test/Stress1.urp
./test2/Notify.exe: ./.fix-multy3
./test2/Notify.sql: ./.fix-multy3
./test2/Notify.urp: ./Makefile ./.cake3/tmp___test2_Notify_in_1 ./.cake3/tmp___test2_Notify_in_2
	cat ./.cake3/tmp___test2_Notify_in_1 > ./test2/Notify.urp
	cat ./.cake3/tmp___test2_Notify_in_2 >> ./test2/Notify.urp
./test2/Simple1.exe: ./.fix-multy4
./test2/Simple1.sql: ./.fix-multy4
./test2/Simple1.urp: ./Makefile ./.cake3/tmp___test2_Simple1_in_1 ./.cake3/tmp___test2_Simple1_in_2
	cat ./.cake3/tmp___test2_Simple1_in_1 > ./test2/Simple1.urp
	cat ./.cake3/tmp___test2_Simple1_in_2 >> ./test2/Simple1.urp
./test2/Stdout.exe: ./.fix-multy5
./test2/Stdout.sql: ./.fix-multy5
./test2/Stdout.urp: ./Makefile ./.cake3/tmp___test2_Stdout_in_1 ./.cake3/tmp___test2_Stdout_in_2
	cat ./.cake3/tmp___test2_Stdout_in_1 > ./test2/Stdout.urp
	cat ./.cake3/tmp___test2_Stdout_in_2 >> ./test2/Stdout.urp
./test2/Stress.exe: ./.fix-multy6
./test2/Stress.sql: ./.fix-multy6
./test2/Stress.urp: ./Makefile ./.cake3/tmp___test2_Stress_in_1 ./.cake3/tmp___test2_Stress_in_2
	cat ./.cake3/tmp___test2_Stress_in_1 > ./test2/Stress.urp
	cat ./.cake3/tmp___test2_Stress_in_2 >> ./test2/Stress.urp
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@
$(call GUARD,UR_CPP):
	rm -f .cake3/GUARD_UR_CPP_*
	touch $@
$(call GUARD,UR_INCL):
	rm -f .cake3/GUARD_UR_INCL_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: ./all
./all: ./.fix-multy1
.PHONY: ./demo/Demo2.db
./demo/Demo2.db: ./.fix-multy1
.PHONY: ./test2/Notify.db
./test2/Notify.db: ./.fix-multy1
.PHONY: ./test2/Stress.db
./test2/Stress.db: ./.fix-multy1
.PHONY: ./test2/Stdout.db
./test2/Stdout.db: ./.fix-multy1
.PHONY: ./test2/Simple1.db
./test2/Simple1.db: ./.fix-multy1
.PHONY: ./test/Stress1.db
./test/Stress1.db: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Notify_in_2
./.cake3/tmp___test2_Notify_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Notify_in_1
./.cake3/tmp___test2_Notify_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___lib_in_2
./.cake3/tmp___lib_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___lib_in_1
./.cake3/tmp___lib_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Stress_in_2
./.cake3/tmp___test2_Stress_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Stress_in_1
./.cake3/tmp___test2_Stress_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Stdout_in_2
./.cake3/tmp___test2_Stdout_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Stdout_in_1
./.cake3/tmp___test2_Stdout_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Simple1_in_2
./.cake3/tmp___test2_Simple1_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test2_Simple1_in_1
./.cake3/tmp___test2_Simple1_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___test_Stress1_in_2
./.cake3/tmp___test_Stress1_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test_Stress1_in_1
./.cake3/tmp___test_Stress1_in_1: ./.fix-multy1
.PHONY: ./demo
./demo: ./.fix-multy1
.PHONY: ./.cake3/tmp___demo_Demo2_in_2
./.cake3/tmp___demo_Demo2_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___demo_Demo2_in_1
./.cake3/tmp___demo_Demo2_in_1: ./.fix-multy1
.PHONY: ./lib
./lib: ./.fix-multy1
.INTERMEDIATE: ./.fix-multy1
./.fix-multy1:
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)
.PHONY: ./CallbackFFI.o
./CallbackFFI.o: ./.fix-multy1
.PHONY: ./demo/Demo2.exe
./demo/Demo2.exe: ./.fix-multy1
.PHONY: ./demo/Demo2.sql
./demo/Demo2.sql: ./.fix-multy1
.PHONY: ./demo/Demo2.urp
./demo/Demo2.urp: ./.fix-multy1
.PHONY: ./lib.urp
./lib.urp: ./.fix-multy1
.PHONY: ./test/Stress1.exe
./test/Stress1.exe: ./.fix-multy1
.PHONY: ./test/Stress1.sql
./test/Stress1.sql: ./.fix-multy1
.PHONY: ./test/Stress1.urp
./test/Stress1.urp: ./.fix-multy1
.PHONY: ./test2/Notify.exe
./test2/Notify.exe: ./.fix-multy1
.PHONY: ./test2/Notify.sql
./test2/Notify.sql: ./.fix-multy1
.PHONY: ./test2/Notify.urp
./test2/Notify.urp: ./.fix-multy1
.PHONY: ./test2/Simple1.exe
./test2/Simple1.exe: ./.fix-multy1
.PHONY: ./test2/Simple1.sql
./test2/Simple1.sql: ./.fix-multy1
.PHONY: ./test2/Simple1.urp
./test2/Simple1.urp: ./.fix-multy1
.PHONY: ./test2/Stdout.exe
./test2/Stdout.exe: ./.fix-multy1
.PHONY: ./test2/Stdout.sql
./test2/Stdout.sql: ./.fix-multy1
.PHONY: ./test2/Stdout.urp
./test2/Stdout.urp: ./.fix-multy1
.PHONY: ./test2/Stress.exe
./test2/Stress.exe: ./.fix-multy1
.PHONY: ./test2/Stress.sql
./test2/Stress.sql: ./.fix-multy1
.PHONY: ./test2/Stress.urp
./test2/Stress.urp: ./.fix-multy1

endif
.PHONY: ./clean
./clean:
	-rm ./.cake3/tmp___demo_Demo2_in_1 ./.cake3/tmp___demo_Demo2_in_2 ./.cake3/tmp___lib_in_1 ./.cake3/tmp___lib_in_2 ./.cake3/tmp___test2_Notify_in_1 ./.cake3/tmp___test2_Notify_in_2 ./.cake3/tmp___test2_Simple1_in_1 ./.cake3/tmp___test2_Simple1_in_2 ./.cake3/tmp___test2_Stdout_in_1 ./.cake3/tmp___test2_Stdout_in_2 ./.cake3/tmp___test2_Stress_in_1 ./.cake3/tmp___test2_Stress_in_2 ./.cake3/tmp___test_Stress1_in_1 ./.cake3/tmp___test_Stress1_in_2 ./CallbackFFI.o ./demo/Demo2.db ./demo/Demo2.exe ./demo/Demo2.sql ./demo/Demo2.urp ./lib.urp ./test/Stress1.db ./test/Stress1.exe ./test/Stress1.sql ./test/Stress1.urp ./test2/Notify.db ./test2/Notify.exe ./test2/Notify.sql ./test2/Notify.urp ./test2/Simple1.db ./test2/Simple1.exe ./test2/Simple1.sql ./test2/Simple1.urp ./test2/Stdout.db ./test2/Stdout.exe ./test2/Stdout.sql ./test2/Stdout.urp ./test2/Stress.db ./test2/Stress.exe ./test2/Stress.sql ./test2/Stress.urp
	-rm -rf .cake3

endif
