# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
URVERSION = $(shell urweb -version)
.PHONY: all
all: ./Test.exe ./Test.sql
.PHONY: clean
clean: 
	rm -rf .cake3 ./Callback.o ./Test.sql ./Test.exe
.PHONY: run
run: ./Test.exe ./Test.sql
	./Test.exe
./Test.exe: .fix-multy1
./Test.urp: ./Test.urp.in
	cat ./Test.urp.in > ./Test.urp
./Test.urp.in: ./Callback.h ./Callback.o ./Test.ur ./Test.urs
	touch ./Test.urp.in
./Callback.o: ./Callback.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL) -o ./Callback.o ./Callback.c
./Test.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./Test.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./Test
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: clean
clean: .fix-multy1
.PHONY: run
run: .fix-multy1
.PHONY: ./Test.exe
./Test.exe: .fix-multy1
.PHONY: ./Test.urp
./Test.urp: .fix-multy1
.PHONY: ./Test.urp.in
./Test.urp.in: .fix-multy1
.PHONY: ./Callback.o
./Callback.o: .fix-multy1
.PHONY: ./Test.sql
./Test.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./Makefile MAIN=1 $(MAKECMDGOALS)

endif
