# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCPP = $(shell $(shell urweb -print-ccompiler) -print-prog-name=g++)
URINCL = -I$(shell urweb -print-cinclude) 
URVERSION = $(shell urweb -version)
.PHONY: all
all: ./test/Test1.db ./test/Test1.exe ./test/Test1.sql ./test/Test2.db ./test/Test2.exe ./test/Test2.sql ./test/Test3.db ./test/Test3.exe ./test/Test3.sql
./test/Test3.db: ./test/Test3.exe ./test/Test3.sql
	dropdb --if-exists Test3
	createdb Test3
	psql -f ./test/Test3.sql Test3
	touch ./test/Test3.db
./test/Test2.db: ./test/Test2.exe ./test/Test2.sql
	dropdb --if-exists Test2
	createdb Test2
	psql -f ./test/Test2.sql Test2
	touch ./test/Test2.db
./test/Test1.db: ./test/Test1.exe ./test/Test1.sql
	dropdb --if-exists Test1
	createdb Test1
	psql -f ./test/Test1.sql Test1
	touch ./test/Test1.db
./test/Test3.exe: .fix-multy3
./test/Test3.urp: ./test/Test3.urp.in
	cat ./test/Test3.urp.in > ./test/Test3.urp
./test/Test3.urp.in: ./lib.urp ./test/Test3.ur ./test/Test3.urs
	touch ./test/Test3.urp.in
./test/Test2.exe: .fix-multy2
./test/Test2.urp: ./test/Test2.urp.in
	cat ./test/Test2.urp.in > ./test/Test2.urp
./test/Test2.urp.in: ./lib.urp ./test/Test2.ur ./test/Test2.urs
	touch ./test/Test2.urp.in
./test/Test1.exe: .fix-multy1
./test/Test1.urp: ./test/Test1.urp.in
	cat ./test/Test1.urp.in > ./test/Test1.urp
./test/Test1.urp.in: ./lib.urp ./test/Test1.ur ./test/Test1.urs
	touch ./test/Test1.urp.in
./lib.urp: ./lib.urp.in
	cat ./lib.urp.in > ./lib.urp
./lib.urp.in: ./Callback.ur ./Callback.urs ./CallbackFFI.h ./CallbackFFI.o
	touch ./lib.urp.in
./CallbackFFI.o: ./CallbackFFI.cpp $(call GUARD,URCPP) $(call GUARD,URINCL)
	$(URCPP) -c $(URINCL) -std=c++11 -o ./CallbackFFI.o ./CallbackFFI.cpp
./test/Test1.sql: .fix-multy1
./test/Test2.sql: .fix-multy2
./test/Test3.sql: .fix-multy3
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./test/Test1.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test/Test1
.INTERMEDIATE: .fix-multy2
.fix-multy2: ./test/Test2.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test/Test2
.INTERMEDIATE: .fix-multy3
.fix-multy3: ./test/Test3.urp $(call GUARD,URVERSION)
	urweb -dbms postgres ./test/Test3
$(call GUARD,URCPP):
	rm -f .cake3/GUARD_URCPP_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

.PHONY: all
all: .fix-multy1
.PHONY: ./test/Test3.db
./test/Test3.db: .fix-multy1
.PHONY: ./test/Test2.db
./test/Test2.db: .fix-multy1
.PHONY: ./test/Test1.db
./test/Test1.db: .fix-multy1
.PHONY: ./test/Test3.exe
./test/Test3.exe: .fix-multy1
.PHONY: ./test/Test3.urp
./test/Test3.urp: .fix-multy1
.PHONY: ./test/Test3.urp.in
./test/Test3.urp.in: .fix-multy1
.PHONY: ./test/Test2.exe
./test/Test2.exe: .fix-multy1
.PHONY: ./test/Test2.urp
./test/Test2.urp: .fix-multy1
.PHONY: ./test/Test2.urp.in
./test/Test2.urp.in: .fix-multy1
.PHONY: ./test/Test1.exe
./test/Test1.exe: .fix-multy1
.PHONY: ./test/Test1.urp
./test/Test1.urp: .fix-multy1
.PHONY: ./test/Test1.urp.in
./test/Test1.urp.in: .fix-multy1
.PHONY: ./lib.urp
./lib.urp: .fix-multy1
.PHONY: ./lib.urp.in
./lib.urp.in: .fix-multy1
.PHONY: ./CallbackFFI.o
./CallbackFFI.o: .fix-multy1
.PHONY: ./test/Test1.sql
./test/Test1.sql: .fix-multy1
.PHONY: ./test/Test2.sql
./test/Test2.sql: .fix-multy1
.PHONY: ./test/Test3.sql
./test/Test3.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./Makefile $(MAKECMDGOALS)

endif
